### PR TITLE
Fix setting context location home/work

### LINKED ISSUE #128: Cannot enter home address
Sequence:
U: what's the weather?
A: What location do you want the weather for?
U: home
A: What is your home address?
U: <enter my address>

Error:
```
Nov 10 12:58:12 giovanni-macbook flatpak[3012]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Nov 10 12:58:12 giovanni-macbook flatpak[3012]:     at resolveUserContext (/app/lib/edu.stanford.Almond/service/node_modules/almond-dialog-agent/lib/dialogs/user_context.js:104:>
Nov 10 12:58:12 giovanni-macbook flatpak[3012]:     at ctr.toJS (/app/lib/edu.stanford.Almond/service/node_modules/thingtalk/lib/ast/values.js:266:15)
Nov 10 12:58:12 giovanni-macbook flatpak[3012]: TypeError: Location is unknown
Nov 10 12:58:12 giovanni-macbook gnome-shell[2787]: msgBody: Almond says: Sorry, I had an error processing your command: Location is unknown
Nov 10 12:58:12 giovanni-macbook flatpak[3012]: Almond Says: Sorry, I had an error processing your command: Location is unknown
```

### LINKED ISSUE #129: Location resolution should account for user's current location
And when ambiguous, pick the closest.
Case in point:

U: what's the weather at stanford
A: Current weather for Stanford, Lincoln County, Kentucky, United States of America: sunny, temperature 13.9 C, wind speed 4.4 m/s, humidity 54.60%, cloudiness 11.70%, fog 0%.

### PR DESCRIPTION
**Pull request by sileix**
fix #128; fix #129

### CODE REVIEW

File: lib/dialogs/user_context.js [hunk 1]
```diff
@@ -98,9 +99,15 @@ module.exports = async function resolveUserContext(dlg, variable) {
 
     let answer = await dlg.ask(type, question);
     if (saveToContext) {
-        var platform = dlg.manager.platform;
-        var sharedPrefs = platform.getSharedPreferences();
+        const platform = dlg.manager.platform;
+        const sharedPrefs = platform.getSharedPreferences();
 
+        if (type === ValueCategory.Location) {
+            const resolved = await lookupLocation(dlg, answer.value.name);
```
Comment (gcampax) [inline lib/dialogs/user_context.js]: You can't do this unconditionally - the answer might be an absolute location already, for example if you click on the location picker in Android (and in the tests).

File: lib/utils.js [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+    } else {
+        return new Ast.Value.Location(new Ast.Location.Absolute(location.latitude, location.longitude, location.display||null));
+    }
+}
+
+function distance(l1, l2) {
+    const diffLat = Math.abs(l1.lat - l2.lat);
+    const diffLon = Math.abs(l1.lon - l2.lon);
+    return Math.sqrt(diffLat ** 2 + diffLon ** 2);
+}
```
Comment (gcampax) [inline lib/utils.js]: This math is wrong, you gotta use elliptic distance. The formula is at https://github.com/stanford-oval/thingtalk/blob/master/lib/builtin/primitive_ops.js

**Review by gcampax — CHANGES_REQUESTED** [review]
